### ISSUE TITLE
How to apply MEND on T5?

### ISSUE THREAD

**Issue by tqfang** [eric-mitchell/mend#12]
Could you kindly provide the codes for editing T5? Or could you point out the names of the layers to be edited? 

I think the names of the edited layers are registered here:
https://github.com/eric-mitchell/mend/blob/e04fdb9cc784188906feffeb171025872933a5a8/algs/mend.py#L256-L263
Could you provide the config.model.inner_params for T5? Thanks a lot!

**Comment by eric-mitchell** [comment]
Hi,

For T5-small, we used a config like:

    name: google/t5-small-ssm-nq
    class_name: AutoModelForSeq2SeqLM
    tokenizer_class: AutoTokenizer
    tokenizer_name: google/t5-small-ssm-nq
    inner_params:
    - encoder.block.6.layer.1.DenseReluDense.wi_0.weight
    - encoder.block.6.layer.1.DenseReluDense.wo.weight
    - encoder.block.7.layer.1.DenseReluDense.wi_0.weight
    - encoder.block.7.layer.1.DenseReluDense.wo.weight
    - decoder.block.6.layer.2.DenseReluDense.wi_0.weight
    - decoder.block.6.layer.2.DenseReluDense.wo.weight
    - decoder.block.7.layer.2.DenseReluDense.wi_0.weight
    - decoder.block.7.layer.2.DenseReluDense.wo.weight

    pt: null
    small_name: t5-small

For larger t5 models, the layer indices change to be the last two blocks of encoder/decoder. Hope that helps- feel free to re-open if you still have questions.
