### ISSUE TITLE
A post about your good repository in the medium

### ISSUE THREAD

**Issue by ahkarami** [eric-mitchell/mend#2]
@eric-mitchell 
Thanks for your great repo. I have written the following brief post for introducing your great repo:
[Fast Model Editing at Scale via Model Editor Networks with Gradient Decomposition (MEND)](https://medium.com/@ah.karami.dl/fast-model-editing-at-scale-via-model-editor-networks-with-gradient-decomposition-mend-7d45f1f373e9)
Best

**Comment by eric-mitchell** [comment]
@ahkarami Thanks so much for the kind words and interest in the project!
