### ISSUE TITLE
How to find the define of __x__ and __delta__ ? 

### ISSUE THREAD

**Issue by sev777** [eric-mitchell/mend#3]
Hi, Mr.Eric, 
I find the code : 
`      param_idx = lambda n, p: self.shape_dict[self.get_shape(p)].index(n) if self.config.mend.shared else None  # noqa: E731
            transformed_factors = {
                n: self.mend[str(tuple(self.get_shape(p)))](p.__x__, p.__delta__, param_idx(n, p))
                for n, p in _inner_params(self.model.named_parameters(), self.config.model.inner_params)
            }`
I want to know where can I find the define of __x__ and __delta__ in code  ? 
Is it in torch or python?
Thank you!

**Comment by eric-mitchell** [comment]
Check out `hooks.py` to see where these are defined, using PyTorch hooks in the forward/backward pass. Feel free to re-open if this doesn't clear things up (and sorry for the delay in responding!).
