### ISSUE TITLE
Can't find 10token data

### ISSUE THREAD

**Issue by omar-s1** [eric-mitchell/mend#6]
Hi, I'm trying to run `python -m run +alg=mend +experiment=gen +model=distilgpt2 data.wiki_webtext=False`, but I get a file not found error for `data/10token/data/self_sample/train.json`. I downloaded 10token from the linked google drive folder and unzipped it to `data/10token`. However, when I unzip it, all I get is a single `10token` file, no `train.json`. Not sure if I'm missing something here. Thanks!

**Comment by eric-mitchell** [comment]
After unzipping the Google Drive file (which contains `10token/data/self_sample/*.json`, you should move the top-level `10token` directory into the `data` directory inside of the top-level `mend` directory. Please re-open if you're still having trouble with this!

**Comment by cin-hubert** [comment]
@salemohamedo the file format is tar.gz 
`tar -xf 10token.zip`
