### ISSUE TITLE
Why Choose QA Task in Batched edits with MEND and ENN? 

### ISSUE THREAD

**Issue by sev777** [eric-mitchell/mend#7]
Editing tasks have three categories: binary classification, QA and generation. In Batched edits, Why choose QA?
And What is the result under finetune(FT)?

Thanks!

**Comment by eric-mitchell** [comment]
Hi- we picked QA fairly arbitrarily; you could try it in the other settings as well! One consideration for the generation setting is that it may be a bit more memory-intensive, as the sequences in the training data are longer. I don't know the results of applying fine-tuning in the batched setting, but you should be able to find out fairly easily with the existing codebase. Let me know if you are having trouble with that, and I'd be happy to help!
