### ISSUE TITLE
not being able to install the requirements

### ISSUE THREAD

**Issue by cameronalonso2** [eric-mitchell/mend#8]
Hi
I am getting the following error when installing the requirements with  `pip install -r requirements.txt` 

Collecting git+git://github.com/eric-mitchell/higher@master (from -r requirements.txt (line 7))
  Cloning git://github.com/eric-mitchell/higher (to revision master) to /tmp/pip-req-build-z1v0erey
  Running command git clone --filter=blob:none --quiet git://github.com/eric-mitchell/higher /tmp/pip-req-build-z1v0erey
  fatal: unable to connect to github.com:
  github.com[0: 192.30.255.113]: errno=Connection timed out

  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet git://github.com/eric-mitchell/higher /tmp/pip-req-build-z1v0erey did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/eric-mitchell/higher /tmp/pip-req-build-z1v0erey did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by himanshubeniwal** [comment]
I am also getting the same error.

**Comment by eric-mitchell** [comment]
@cameronalonso2 @himanshubeniwal Sorry for the trouble here, and the delay in responding. I've updated `requirements.txt` to fix this issue- apparently https: rather than git: is needed now in `requirements.txt` for pip to work. I'm closing this issue now, but feel free to re-open if you're still having any problems!
